//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWe_June.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ServiceWe_June.localhost.HelloWorldResponse HelloWorld(ServiceWe_June.localhost.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertAutor", ReplyAction="*")]
        ServiceWe_June.localhost.insertAutorResponse insertAutor(ServiceWe_June.localhost.insertAutorRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCarnet", ReplyAction="*")]
        ServiceWe_June.localhost.insertCarnetResponse insertCarnet(ServiceWe_June.localhost.insertCarnetRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertLibros", ReplyAction="*")]
        ServiceWe_June.localhost.insertLibrosResponse insertLibros(ServiceWe_June.localhost.insertLibrosRequest request);
        
        // CODEGEN: Generating message contract since element name libro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPrestamo", ReplyAction="*")]
        ServiceWe_June.localhost.insertPrestamoResponse insertPrestamo(ServiceWe_June.localhost.insertPrestamoRequest request);
        
        // CODEGEN: Generating message contract since element name libro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertReserva", ReplyAction="*")]
        ServiceWe_June.localhost.insertReservaResponse insertReserva(ServiceWe_June.localhost.insertReservaRequest request);
        
        // CODEGEN: Generating message contract since element name libro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deletePrestamo", ReplyAction="*")]
        ServiceWe_June.localhost.deletePrestamoResponse deletePrestamo(ServiceWe_June.localhost.deletePrestamoRequest request);
        
        // CODEGEN: Generating message contract since element name libro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteReserva", ReplyAction="*")]
        ServiceWe_June.localhost.deleteReservaResponse deleteReserva(ServiceWe_June.localhost.deleteReservaRequest request);
        
        // CODEGEN: Generating message contract since element name libro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getReservasLibro", ReplyAction="*")]
        ServiceWe_June.localhost.getReservasLibroResponse getReservasLibro(ServiceWe_June.localhost.getReservasLibroRequest request);
        
        // CODEGEN: Generating message contract since element name getReservasCarnetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getReservasCarnet", ReplyAction="*")]
        ServiceWe_June.localhost.getReservasCarnetResponse getReservasCarnet(ServiceWe_June.localhost.getReservasCarnetRequest request);
        
        // CODEGEN: Generating message contract since element name libro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comprobarReserva", ReplyAction="*")]
        ServiceWe_June.localhost.comprobarReservaResponse comprobarReserva(ServiceWe_June.localhost.comprobarReservaRequest request);
        
        // CODEGEN: Generating message contract since element name libro from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPrestamosLibro", ReplyAction="*")]
        ServiceWe_June.localhost.getPrestamosLibroResponse getPrestamosLibro(ServiceWe_June.localhost.getPrestamosLibroRequest request);
        
        // CODEGEN: Generating message contract since element name getPrestamosCarnetResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPrestamosCarnet", ReplyAction="*")]
        ServiceWe_June.localhost.getPrestamosCarnetResponse getPrestamosCarnet(ServiceWe_June.localhost.getPrestamosCarnetRequest request);
        
        // CODEGEN: Generating message contract since element name TopFiveResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TopFive", ReplyAction="*")]
        ServiceWe_June.localhost.TopFiveResponse TopFive(ServiceWe_June.localhost.TopFiveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ServiceWe_June.localhost.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ServiceWe_June.localhost.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertAutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertAutor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertAutorRequestBody Body;
        
        public insertAutorRequest() {
        }
        
        public insertAutorRequest(ServiceWe_June.localhost.insertAutorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertAutorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public insertAutorRequestBody() {
        }
        
        public insertAutorRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertAutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertAutorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertAutorResponseBody Body;
        
        public insertAutorResponse() {
        }
        
        public insertAutorResponse(ServiceWe_June.localhost.insertAutorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertAutorResponseBody {
        
        public insertAutorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCarnetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCarnet", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertCarnetRequestBody Body;
        
        public insertCarnetRequest() {
        }
        
        public insertCarnetRequest(ServiceWe_June.localhost.insertCarnetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCarnetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int dpi;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int telefono;
        
        public insertCarnetRequestBody() {
        }
        
        public insertCarnetRequestBody(string nombre, int dpi, int telefono) {
            this.nombre = nombre;
            this.dpi = dpi;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCarnetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCarnetResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertCarnetResponseBody Body;
        
        public insertCarnetResponse() {
        }
        
        public insertCarnetResponse(ServiceWe_June.localhost.insertCarnetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCarnetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCarnetResult;
        
        public insertCarnetResponseBody() {
        }
        
        public insertCarnetResponseBody(string insertCarnetResult) {
            this.insertCarnetResult = insertCarnetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertLibrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertLibros", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertLibrosRequestBody Body;
        
        public insertLibrosRequest() {
        }
        
        public insertLibrosRequest(ServiceWe_June.localhost.insertLibrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertLibrosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int existencias;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int paginas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Autor;
        
        public insertLibrosRequestBody() {
        }
        
        public insertLibrosRequestBody(string nombre, int existencias, int paginas, string tema, string Autor) {
            this.nombre = nombre;
            this.existencias = existencias;
            this.paginas = paginas;
            this.tema = tema;
            this.Autor = Autor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertLibrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertLibrosResponseBody Body;
        
        public insertLibrosResponse() {
        }
        
        public insertLibrosResponse(ServiceWe_June.localhost.insertLibrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertLibrosResponseBody {
        
        public insertLibrosResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPrestamo", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertPrestamoRequestBody Body;
        
        public insertPrestamoRequest() {
        }
        
        public insertPrestamoRequest(ServiceWe_June.localhost.insertPrestamoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertPrestamoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string libro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int carnet;
        
        public insertPrestamoRequestBody() {
        }
        
        public insertPrestamoRequestBody(string libro, int carnet) {
            this.libro = libro;
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPrestamoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertPrestamoResponseBody Body;
        
        public insertPrestamoResponse() {
        }
        
        public insertPrestamoResponse(ServiceWe_June.localhost.insertPrestamoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertPrestamoResponseBody {
        
        public insertPrestamoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertReserva", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertReservaRequestBody Body;
        
        public insertReservaRequest() {
        }
        
        public insertReservaRequest(ServiceWe_June.localhost.insertReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string libro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int carnet;
        
        public insertReservaRequestBody() {
        }
        
        public insertReservaRequestBody(string libro, int carnet) {
            this.libro = libro;
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.insertReservaResponseBody Body;
        
        public insertReservaResponse() {
        }
        
        public insertReservaResponse(ServiceWe_June.localhost.insertReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertReservaResponseBody {
        
        public insertReservaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletePrestamoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletePrestamo", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.deletePrestamoRequestBody Body;
        
        public deletePrestamoRequest() {
        }
        
        public deletePrestamoRequest(ServiceWe_June.localhost.deletePrestamoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deletePrestamoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string libro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int carnet;
        
        public deletePrestamoRequestBody() {
        }
        
        public deletePrestamoRequestBody(string libro, int carnet) {
            this.libro = libro;
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletePrestamoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletePrestamoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.deletePrestamoResponseBody Body;
        
        public deletePrestamoResponse() {
        }
        
        public deletePrestamoResponse(ServiceWe_June.localhost.deletePrestamoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deletePrestamoResponseBody {
        
        public deletePrestamoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteReserva", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.deleteReservaRequestBody Body;
        
        public deleteReservaRequest() {
        }
        
        public deleteReservaRequest(ServiceWe_June.localhost.deleteReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string libro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int carnet;
        
        public deleteReservaRequestBody() {
        }
        
        public deleteReservaRequestBody(string libro, int carnet) {
            this.libro = libro;
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.deleteReservaResponseBody Body;
        
        public deleteReservaResponse() {
        }
        
        public deleteReservaResponse(ServiceWe_June.localhost.deleteReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteReservaResponseBody {
        
        public deleteReservaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservasLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReservasLibro", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getReservasLibroRequestBody Body;
        
        public getReservasLibroRequest() {
        }
        
        public getReservasLibroRequest(ServiceWe_June.localhost.getReservasLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReservasLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string libro;
        
        public getReservasLibroRequestBody() {
        }
        
        public getReservasLibroRequestBody(string libro) {
            this.libro = libro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservasLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReservasLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getReservasLibroResponseBody Body;
        
        public getReservasLibroResponse() {
        }
        
        public getReservasLibroResponse(ServiceWe_June.localhost.getReservasLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReservasLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReservasLibroResult;
        
        public getReservasLibroResponseBody() {
        }
        
        public getReservasLibroResponseBody(string getReservasLibroResult) {
            this.getReservasLibroResult = getReservasLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservasCarnetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReservasCarnet", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getReservasCarnetRequestBody Body;
        
        public getReservasCarnetRequest() {
        }
        
        public getReservasCarnetRequest(ServiceWe_June.localhost.getReservasCarnetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReservasCarnetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int carnet;
        
        public getReservasCarnetRequestBody() {
        }
        
        public getReservasCarnetRequestBody(int carnet) {
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReservasCarnetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReservasCarnetResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getReservasCarnetResponseBody Body;
        
        public getReservasCarnetResponse() {
        }
        
        public getReservasCarnetResponse(ServiceWe_June.localhost.getReservasCarnetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReservasCarnetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReservasCarnetResult;
        
        public getReservasCarnetResponseBody() {
        }
        
        public getReservasCarnetResponseBody(string getReservasCarnetResult) {
            this.getReservasCarnetResult = getReservasCarnetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprobarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprobarReserva", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.comprobarReservaRequestBody Body;
        
        public comprobarReservaRequest() {
        }
        
        public comprobarReservaRequest(ServiceWe_June.localhost.comprobarReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comprobarReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string libro;
        
        public comprobarReservaRequestBody() {
        }
        
        public comprobarReservaRequestBody(int carnet, string libro) {
            this.carnet = carnet;
            this.libro = libro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprobarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprobarReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.comprobarReservaResponseBody Body;
        
        public comprobarReservaResponse() {
        }
        
        public comprobarReservaResponse(ServiceWe_June.localhost.comprobarReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comprobarReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string comprobarReservaResult;
        
        public comprobarReservaResponseBody() {
        }
        
        public comprobarReservaResponseBody(string comprobarReservaResult) {
            this.comprobarReservaResult = comprobarReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrestamosLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPrestamosLibro", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getPrestamosLibroRequestBody Body;
        
        public getPrestamosLibroRequest() {
        }
        
        public getPrestamosLibroRequest(ServiceWe_June.localhost.getPrestamosLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPrestamosLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string libro;
        
        public getPrestamosLibroRequestBody() {
        }
        
        public getPrestamosLibroRequestBody(string libro) {
            this.libro = libro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrestamosLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPrestamosLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getPrestamosLibroResponseBody Body;
        
        public getPrestamosLibroResponse() {
        }
        
        public getPrestamosLibroResponse(ServiceWe_June.localhost.getPrestamosLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPrestamosLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPrestamosLibroResult;
        
        public getPrestamosLibroResponseBody() {
        }
        
        public getPrestamosLibroResponseBody(string getPrestamosLibroResult) {
            this.getPrestamosLibroResult = getPrestamosLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrestamosCarnetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPrestamosCarnet", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getPrestamosCarnetRequestBody Body;
        
        public getPrestamosCarnetRequest() {
        }
        
        public getPrestamosCarnetRequest(ServiceWe_June.localhost.getPrestamosCarnetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPrestamosCarnetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int carnet;
        
        public getPrestamosCarnetRequestBody() {
        }
        
        public getPrestamosCarnetRequestBody(int carnet) {
            this.carnet = carnet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrestamosCarnetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPrestamosCarnetResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.getPrestamosCarnetResponseBody Body;
        
        public getPrestamosCarnetResponse() {
        }
        
        public getPrestamosCarnetResponse(ServiceWe_June.localhost.getPrestamosCarnetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPrestamosCarnetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPrestamosCarnetResult;
        
        public getPrestamosCarnetResponseBody() {
        }
        
        public getPrestamosCarnetResponseBody(string getPrestamosCarnetResult) {
            this.getPrestamosCarnetResult = getPrestamosCarnetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TopFiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TopFive", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.TopFiveRequestBody Body;
        
        public TopFiveRequest() {
        }
        
        public TopFiveRequest(ServiceWe_June.localhost.TopFiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TopFiveRequestBody {
        
        public TopFiveRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TopFiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TopFiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceWe_June.localhost.TopFiveResponseBody Body;
        
        public TopFiveResponse() {
        }
        
        public TopFiveResponse(ServiceWe_June.localhost.TopFiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TopFiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TopFiveResult;
        
        public TopFiveResponseBody() {
        }
        
        public TopFiveResponseBody(string TopFiveResult) {
            this.TopFiveResult = TopFiveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ServiceWe_June.localhost.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceWe_June.localhost.WebService1Soap>, ServiceWe_June.localhost.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.HelloWorldResponse ServiceWe_June.localhost.WebService1Soap.HelloWorld(ServiceWe_June.localhost.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ServiceWe_June.localhost.HelloWorldRequest inValue = new ServiceWe_June.localhost.HelloWorldRequest();
            inValue.Body = new ServiceWe_June.localhost.HelloWorldRequestBody();
            ServiceWe_June.localhost.HelloWorldResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.insertAutorResponse ServiceWe_June.localhost.WebService1Soap.insertAutor(ServiceWe_June.localhost.insertAutorRequest request) {
            return base.Channel.insertAutor(request);
        }
        
        public void insertAutor(string nombre) {
            ServiceWe_June.localhost.insertAutorRequest inValue = new ServiceWe_June.localhost.insertAutorRequest();
            inValue.Body = new ServiceWe_June.localhost.insertAutorRequestBody();
            inValue.Body.nombre = nombre;
            ServiceWe_June.localhost.insertAutorResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).insertAutor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.insertCarnetResponse ServiceWe_June.localhost.WebService1Soap.insertCarnet(ServiceWe_June.localhost.insertCarnetRequest request) {
            return base.Channel.insertCarnet(request);
        }
        
        public string insertCarnet(string nombre, int dpi, int telefono) {
            ServiceWe_June.localhost.insertCarnetRequest inValue = new ServiceWe_June.localhost.insertCarnetRequest();
            inValue.Body = new ServiceWe_June.localhost.insertCarnetRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.dpi = dpi;
            inValue.Body.telefono = telefono;
            ServiceWe_June.localhost.insertCarnetResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).insertCarnet(inValue);
            return retVal.Body.insertCarnetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.insertLibrosResponse ServiceWe_June.localhost.WebService1Soap.insertLibros(ServiceWe_June.localhost.insertLibrosRequest request) {
            return base.Channel.insertLibros(request);
        }
        
        public void insertLibros(string nombre, int existencias, int paginas, string tema, string Autor) {
            ServiceWe_June.localhost.insertLibrosRequest inValue = new ServiceWe_June.localhost.insertLibrosRequest();
            inValue.Body = new ServiceWe_June.localhost.insertLibrosRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.existencias = existencias;
            inValue.Body.paginas = paginas;
            inValue.Body.tema = tema;
            inValue.Body.Autor = Autor;
            ServiceWe_June.localhost.insertLibrosResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).insertLibros(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.insertPrestamoResponse ServiceWe_June.localhost.WebService1Soap.insertPrestamo(ServiceWe_June.localhost.insertPrestamoRequest request) {
            return base.Channel.insertPrestamo(request);
        }
        
        public void insertPrestamo(string libro, int carnet) {
            ServiceWe_June.localhost.insertPrestamoRequest inValue = new ServiceWe_June.localhost.insertPrestamoRequest();
            inValue.Body = new ServiceWe_June.localhost.insertPrestamoRequestBody();
            inValue.Body.libro = libro;
            inValue.Body.carnet = carnet;
            ServiceWe_June.localhost.insertPrestamoResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).insertPrestamo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.insertReservaResponse ServiceWe_June.localhost.WebService1Soap.insertReserva(ServiceWe_June.localhost.insertReservaRequest request) {
            return base.Channel.insertReserva(request);
        }
        
        public void insertReserva(string libro, int carnet) {
            ServiceWe_June.localhost.insertReservaRequest inValue = new ServiceWe_June.localhost.insertReservaRequest();
            inValue.Body = new ServiceWe_June.localhost.insertReservaRequestBody();
            inValue.Body.libro = libro;
            inValue.Body.carnet = carnet;
            ServiceWe_June.localhost.insertReservaResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).insertReserva(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.deletePrestamoResponse ServiceWe_June.localhost.WebService1Soap.deletePrestamo(ServiceWe_June.localhost.deletePrestamoRequest request) {
            return base.Channel.deletePrestamo(request);
        }
        
        public void deletePrestamo(string libro, int carnet) {
            ServiceWe_June.localhost.deletePrestamoRequest inValue = new ServiceWe_June.localhost.deletePrestamoRequest();
            inValue.Body = new ServiceWe_June.localhost.deletePrestamoRequestBody();
            inValue.Body.libro = libro;
            inValue.Body.carnet = carnet;
            ServiceWe_June.localhost.deletePrestamoResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).deletePrestamo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.deleteReservaResponse ServiceWe_June.localhost.WebService1Soap.deleteReserva(ServiceWe_June.localhost.deleteReservaRequest request) {
            return base.Channel.deleteReserva(request);
        }
        
        public void deleteReserva(string libro, int carnet) {
            ServiceWe_June.localhost.deleteReservaRequest inValue = new ServiceWe_June.localhost.deleteReservaRequest();
            inValue.Body = new ServiceWe_June.localhost.deleteReservaRequestBody();
            inValue.Body.libro = libro;
            inValue.Body.carnet = carnet;
            ServiceWe_June.localhost.deleteReservaResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).deleteReserva(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.getReservasLibroResponse ServiceWe_June.localhost.WebService1Soap.getReservasLibro(ServiceWe_June.localhost.getReservasLibroRequest request) {
            return base.Channel.getReservasLibro(request);
        }
        
        public string getReservasLibro(string libro) {
            ServiceWe_June.localhost.getReservasLibroRequest inValue = new ServiceWe_June.localhost.getReservasLibroRequest();
            inValue.Body = new ServiceWe_June.localhost.getReservasLibroRequestBody();
            inValue.Body.libro = libro;
            ServiceWe_June.localhost.getReservasLibroResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).getReservasLibro(inValue);
            return retVal.Body.getReservasLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.getReservasCarnetResponse ServiceWe_June.localhost.WebService1Soap.getReservasCarnet(ServiceWe_June.localhost.getReservasCarnetRequest request) {
            return base.Channel.getReservasCarnet(request);
        }
        
        public string getReservasCarnet(int carnet) {
            ServiceWe_June.localhost.getReservasCarnetRequest inValue = new ServiceWe_June.localhost.getReservasCarnetRequest();
            inValue.Body = new ServiceWe_June.localhost.getReservasCarnetRequestBody();
            inValue.Body.carnet = carnet;
            ServiceWe_June.localhost.getReservasCarnetResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).getReservasCarnet(inValue);
            return retVal.Body.getReservasCarnetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.comprobarReservaResponse ServiceWe_June.localhost.WebService1Soap.comprobarReserva(ServiceWe_June.localhost.comprobarReservaRequest request) {
            return base.Channel.comprobarReserva(request);
        }
        
        public string comprobarReserva(int carnet, string libro) {
            ServiceWe_June.localhost.comprobarReservaRequest inValue = new ServiceWe_June.localhost.comprobarReservaRequest();
            inValue.Body = new ServiceWe_June.localhost.comprobarReservaRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.libro = libro;
            ServiceWe_June.localhost.comprobarReservaResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).comprobarReserva(inValue);
            return retVal.Body.comprobarReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.getPrestamosLibroResponse ServiceWe_June.localhost.WebService1Soap.getPrestamosLibro(ServiceWe_June.localhost.getPrestamosLibroRequest request) {
            return base.Channel.getPrestamosLibro(request);
        }
        
        public string getPrestamosLibro(string libro) {
            ServiceWe_June.localhost.getPrestamosLibroRequest inValue = new ServiceWe_June.localhost.getPrestamosLibroRequest();
            inValue.Body = new ServiceWe_June.localhost.getPrestamosLibroRequestBody();
            inValue.Body.libro = libro;
            ServiceWe_June.localhost.getPrestamosLibroResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).getPrestamosLibro(inValue);
            return retVal.Body.getPrestamosLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.getPrestamosCarnetResponse ServiceWe_June.localhost.WebService1Soap.getPrestamosCarnet(ServiceWe_June.localhost.getPrestamosCarnetRequest request) {
            return base.Channel.getPrestamosCarnet(request);
        }
        
        public string getPrestamosCarnet(int carnet) {
            ServiceWe_June.localhost.getPrestamosCarnetRequest inValue = new ServiceWe_June.localhost.getPrestamosCarnetRequest();
            inValue.Body = new ServiceWe_June.localhost.getPrestamosCarnetRequestBody();
            inValue.Body.carnet = carnet;
            ServiceWe_June.localhost.getPrestamosCarnetResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).getPrestamosCarnet(inValue);
            return retVal.Body.getPrestamosCarnetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceWe_June.localhost.TopFiveResponse ServiceWe_June.localhost.WebService1Soap.TopFive(ServiceWe_June.localhost.TopFiveRequest request) {
            return base.Channel.TopFive(request);
        }
        
        public string TopFive() {
            ServiceWe_June.localhost.TopFiveRequest inValue = new ServiceWe_June.localhost.TopFiveRequest();
            inValue.Body = new ServiceWe_June.localhost.TopFiveRequestBody();
            ServiceWe_June.localhost.TopFiveResponse retVal = ((ServiceWe_June.localhost.WebService1Soap)(this)).TopFive(inValue);
            return retVal.Body.TopFiveResult;
        }
    }
}
